name: BedWars-SpectatorOptions
version: '1.1'
main: me.kiiya.spectatoroptions.SpectatorOptions
author: Kiiya
authors:
  - Kiiya
description: SpectatorOptions for BedWars
softdepend: [ BedWars1058, BedWars2023, PlaceholderAPI ]
commands:
    bwso:
        description: Open SpectatorOptions GUI

