name: BedWars-SpectatorOptions
version: '1.0-SNAPSHOT'
main: me.kiiya.spectatoroptions.SpectatorOptions
author: Kiiya
authors:
  - Kiiya
description: SpectatorOptions for BedWars
api-version: 1.8
softdepend: [ BedWars1058, BedWars2023, PlaceholderAPI ]
commands:
    bwso:
        description: Open SpectatorOptions GUI

